In [26]:
import numpy as np
import pandas as pd
import textwrap
import nltk
from nltk import word_tokenize
from nltk.tokenize.treebank import TreebankWordDetokenizer

In [27]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [28]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [29]:
df = pd.read_csv('bbc-text.csv')

In [30]:
df.head()

        category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [31]:
labels = set(df['category'])
labels

{'business', 'entertainment', 'politics', 'sport', 'tech'}

In [32]:
# Pick a label whose data we want to train from
label = 'business'

In [33]:
texts = df[df['category'] == label]['text']
texts.head()

1     worldcom boss  left books alone  former worldc...
11    virgin blue shares plummet 20% shares in austr...
12    crude oil prices back above $50 cold weather a...
15    s korean credit card firm rescued south korea ...
18    japanese banking battle at an end japan s sumi...
Name: text, dtype: object

In [34]:
# collect counts
probs = {} # key: (w(t-1), w(t+1)), value: {w(t): count(w(t))}

for doc in texts:
  lines = doc.split("\n")
  for line in lines:
    tokens = word_tokenize(line)
    for i in range(len(tokens) - 2):
      t_0 = tokens[i]
      t_1 = tokens[i + 1]
      t_2 = tokens[i + 2]
      key = (t_0, t_2)
      if key not in probs:
        probs[key] = {}

      # add count for middle token
      if t_1 not in probs[key]:
        probs[key][t_1] = 1
      else:
        probs[key][t_1] += 1

In [35]:
# normalize probabilities key is surrounding word and d dict
for key, d in probs.items():
  # d should represent a distribution
  total = sum(d.values())
  #k is middle word v is value
  for k, v in d.items():
    d[k] = v / total

In [36]:
probs

{('worldcom', 'left'): {'boss': 1.0},
 ('boss', 'books'): {'left': 1.0},
 ('left', 'alone'): {'books': 1.0},
 ('books', 'former'): {'alone': 1.0},
 ('alone', 'worldcom'): {'former': 1.0},
 ('former', 'boss'): {'worldcom': 0.625, 'yukos': 0.25, 'shell': 0.125},
 ('worldcom', 'bernie'): {'boss': 0.7142857142857143,
  'chief': 0.2857142857142857},
 ('boss', 'ebbers'): {'bernie': 0.8333333333333334,
  'bernard': 0.16666666666666666},
 ('bernie', 'who'): {'ebbers': 0.5, 'banton': 0.5},
 ('ebbers', 'is'): {'who': 0.5, 'trial': 0.5},
 ('who', 'accused'): {'is': 1.0},
 ('is', 'of'): {'accused': 0.08823529411764706,
  'part': 0.20588235294117646,
  'one': 0.47058823529411764,
  'because': 0.058823529411764705,
  'symbolic': 0.029411764705882353,
  'confident': 0.058823529411764705,
  'also': 0.029411764705882353,
  'tens': 0.029411764705882353,
  'hopeful': 0.029411764705882353},
 ('accused', 'overseeing'): {'of': 1.0},
 ('of', 'an'): {'overseeing': 0.5,
  'kfb': 0.125,
  'opening': 0.125,
  'aara': 0.125,
  'half': 0.125},
 ('overseeing', '$'): {'an': 1.0},
 ('an', '11bn'): {'$': 1.0},
 ('$', '('): {'11bn': 0.03389830508474576,
  '850m': 0.00847457627118644,
  '800m': 0.0423728813559322,
  '1.1bn': 0.01694915254237288,
  '280bn': 0.025423728813559324,
  '2bn': 0.00847457627118644,
  '48bn': 0.00847457627118644,
  '20bn': 0.01694915254237288,
  '27.5bn': 0.025423728813559324,
  '5.4bn': 0.00847457627118644,
  '671.7bn': 0.00847457627118644,
  '10bn': 0.03389830508474576,
  '5bn': 0.025423728813559324,
  '28.3bn': 0.00847457627118644,
  '327m': 0.00847457627118644,
  '186m': 0.00847457627118644,
  '9.4bn': 0.01694915254237288,
  '3.3bn': 0.00847457627118644,
  '17.6m': 0.00847457627118644,
  '27bn': 0.025423728813559324,
  '9bn': 0.00847457627118644,
  '2.7bn': 0.00847457627118644,
  '434m': 0.00847457627118644,
  '412bn': 0.00847457627118644,
  '100m': 0.01694915254237288,
  '86m': 0.00847457627118644,
  '17bn': 0.00847457627118644,
  '1.5m': 0.00847457627118644,
  '11.5bn': 0.00847457627118644,
  '50bn': 0.00847457627118644,
  '102.6bn': 0.00847457627118644,
  '9.3bn': 0.00847457627118644,
  '560m': 0.00847457627118644,
  '200m': 0.00847457627118644,
  '700m': 0.01694915254237288,
  '1.07bn': 0.01694915254237288,
  '5.37bn': 0.00847457627118644,
  '5.15': 0.00847457627118644,
  '1bn': 0.01694915254237288,
  '6.75bn': 0.00847457627118644,
  '500m': 0.01694915254237288,
  '676m': 0.00847457627118644,
  '375m': 0.00847457627118644,
  '630m': 0.00847457627118644,
  '16.2bn': 0.00847457627118644,
  '3.65bn': 0.00847457627118644,
  '368bn': 0.00847457627118644,
  '3bn': 0.00847457627118644,
  '168m': 0.00847457627118644,
  '261.9m': 0.00847457627118644,
  '4.9m': 0.00847457627118644,
  '40bn': 0.00847457627118644,
  '32bn': 0.00847457627118644,
  '180bn': 0.00847457627118644,
  '155.2bn': 0.00847457627118644,
  '2.95bn': 0.00847457627118644,
  '42bn': 0.00847457627118644,
  '105bn': 0.00847457627118644,
  '3.5bn': 0.01694915254237288,
  '458.4m': 0.00847457627118644,
  '45bn': 0.00847457627118644,
  '600m': 0.00847457627118644,
  '14.5m': 0.00847457627118644,
  '6bn': 0.01694915254237288,
  '4bn': 0.00847457627118644,
  '717m': 0.00847457627118644,
  '6.8bn': 0.00847457627118644,
  '16bn': 0.00847457627118644,
  '1.5bn': 0.00847457627118644,
  '3.1bn': 0.00847457627118644,
  '349.4bn': 0.00847457627118644,
  '445.1bn': 0.00847457627118644,
  '25.4bn': 0.00847457627118644,
  '750m': 0.00847457627118644,
  '300bn': 0.00847457627118644,
  '1.3bn': 0.00847457627118644,
  '16.6bn': 0.00847457627118644,
  '515m': 0.00847457627118644,
  '260m': 0.00847457627118644,
  '6.3bn': 0.00847457627118644,
  '220m': 0.00847457627118644,
  '55.5bn': 0.00847457627118644,
  '499': 0.00847457627118644,
  '8.5bn': 0.00847457627118644,
  '1m': 0.00847457627118644,
  '339m': 0.00847457627118644,
  '546m': 0.00847457627118644,
  '1.8bn': 0.00847457627118644,
  '54m': 0.00847457627118644,
  '900m': 0.00847457627118644},
 ('11bn', '£5.8bn'): {'(': 1.0},
 ('(', ')'): {'£5.8bn': 0.003703703703703704,
  'mtfg': 0.003703703703703704,
  'aig': 0.003703703703703704,
  '£415m': 0.003703703703703704,
  'pwc': 0.007407407407407408,
  'nato': 0.003703703703703704,
  '£424m': 0.011111111111111112,
  'fda': 0.007407407407407408,
  '£581m': 0.003703703703703704,
  '£155bn': 0.007407407407407408,
  'ntpc': 0.003703703703703704,
  'gm': 0.018518518518518517,
  '£1.06bn': 0.003703703703703704,
  '£25.5bn': 0.003703703703703704,
  'gdp': 0.025925925925925925,
  'tuc': 0.003703703703703704,
  '£11bn': 0.003703703703703704,
  '£13bn': 0.007407407407407408,
  'sec': 0.022222222222222223,
  '£3.7bn': 0.003703703703703704,
  'sepa': 0.003703703703703704,
  'mw': 0.007407407407407408,
  '£484bn': 0.003703703703703704,
  'nhtsa': 0.003703703703703704,
  'suvs': 0.011111111111111112,
  'us': 0.003703703703703704,
  '£5.17bn': 0.003703703703703704,
  '£2.6bn': 0.011111111111111112,
  '£149bn': 0.003703703703703704,
  'meti': 0.003703703703703704,
  '£15.2bn': 0.003703703703703704,
  'listing': 0.003703703703703704,
  'lse': 0.018518518518518517,
  'apacs': 0.007407407407407408,
  'wto': 0.018518518518518517,
  'ons': 0.022222222222222223,
  'bse': 0.003703703703703704,
  '£429m': 0.003703703703703704,
  'acc': 0.007407407407407408,
  '£568m': 0.003703703703703704,
  '£1.8bn': 0.007407407407407408,
  'kfb': 0.003703703703703704,
  'mpc': 0.011111111111111112,
  'bcc': 0.014814814814814815,
  'atr': 0.003703703703703704,
  '£9.49m': 0.003703703703703704,
  '£14bn': 0.011111111111111112,
  'who': 0.003703703703703704,
  '£4.6bn': 0.003703703703703704,
  'ofheo': 0.007407407407407408,
  '£1.4bn': 0.003703703703703704,
  'itpc': 0.003703703703703704,
  '£231m': 0.003703703703703704,
  'ecb': 0.003703703703703704,
  '£10.6bn': 0.003703703703703704,
  '£211.6bn': 0.003703703703703704,
  'ids': 0.003703703703703704,
  'kdb': 0.003703703703703704,
  'ism': 0.007407407407407408,
  'suv': 0.003703703703703704,
  '£52m': 0.007407407407407408,
  '£46m': 0.003703703703703704,
  'ipcl': 0.003703703703703704,
  '£6.1bn': 0.003703703703703704,
  'ongc': 0.007407407407407408,
  'imf': 0.025925925925925925,
  'iff': 0.003703703703703704,
  '£5.38bn': 0.003703703703703704,
  'g8': 0.003703703703703704,
  '£26.69bn': 0.003703703703703704,
  '£53.51bn': 0.003703703703703704,
  'negotiations': 0.003703703703703704,
  '£5bn': 0.007407407407407408,
  '£291m': 0.003703703703703704,
  'ppi': 0.007407407407407408,
  'meetings': 0.003703703703703704,
  'niesr': 0.003703703703703704,
  '£374m': 0.007407407407407408,
  'cbi': 0.007407407407407408,
  '£558m': 0.007407407407407408,
  'ipo': 0.003703703703703704,
  'unece': 0.003703703703703704,
  'fsa': 0.007407407407407408,
  'aefa': 0.003703703703703704,
  '£5.3bn': 0.003703703703703704,
  '£2.86bn': 0.003703703703703704,
  '£3.90': 0.003703703703703704,
  '£514m': 0.003703703703703704,
  '£428m': 0.003703703703703704,
  '£3.6bn': 0.007407407407407408,
  'db': 0.003703703703703704,
  '£350m': 0.003703703703703704,
  '£352m': 0.003703703703703704,
  '£195.3m': 0.003703703703703704,
  '£481.5m': 0.003703703703703704,
  'ilo': 0.007407407407407408,
  'eia': 0.003703703703703704,
  '£8.7bn': 0.003703703703703704,
  '£1.97bn': 0.003703703703703704,
  'assets': 0.003703703703703704,
  '£197bn': 0.003703703703703704,
  'cbo': 0.003703703703703704,
  'ibge': 0.003703703703703704,
  'christmas': 0.003703703703703704,
  'growth': 0.003703703703703704,
  'smfg': 0.003703703703703704,
  '£537bn': 0.003703703703703704,
  '£5.7bn': 0.007407407407407408,
  '£89m': 0.003703703703703704,
  '£378.8m': 0.003703703703703704,
  '£5.18bn': 0.003703703703703704,
  '£135.6m': 0.003703703703703704,
  'ncci': 0.003703703703703704,
  '£21bn': 0.003703703703703704,
  'nioc': 0.003703703703703704,
  'cml': 0.003703703703703704,
  'fomc': 0.003703703703703704,
  '£96bn': 0.003703703703703704,
  'citu': 0.003703703703703704,
  '£82.8bn': 0.003703703703703704,
  'nyse': 0.003703703703703704,
  '£14.5bn': 0.007407407407407408,
  'fao': 0.003703703703703704,
  'ea': 0.003703703703703704,
  '£1.57bn': 0.003703703703703704,
  'cvrd': 0.003703703703703704,
  'pml': 0.003703703703703704,
  'boe': 0.003703703703703704,
  'pipa': 0.003703703703703704,
  '£1.99bn': 0.003703703703703704,
  'wttc': 0.007407407407407408,
  '£21.5bn': 0.003703703703703704,
  '£54bn': 0.003703703703703704,
  'icbc': 0.003703703703703704,
  '£24bn': 0.003703703703703704,
  'all': 0.003703703703703704,
  '£309m': 0.003703703703703704,
  '£7.74m': 0.003703703703703704,
  'ipc': 0.003703703703703704,
  'cochilco': 0.003703703703703704,
  '£3.12bn': 0.003703703703703704,
  'lng': 0.003703703703703704,
  '£2.1bn': 0.003703703703703704,
  'mfa': 0.003703703703703704,
  'adb': 0.003703703703703704,
  '£379m': 0.003703703703703704,
  'odpm': 0.003703703703703704,
  '£8.5bn': 0.007407407407407408,
  '£800m': 0.003703703703703704,
  'pibs': 0.003703703703703704,
  'cpi': 0.003703703703703704,
  '£265.9bn': 0.003703703703703704,
  'iadb': 0.003703703703703704,
  'eclac': 0.003703703703703704,
  'apec': 0.003703703703703704,
  'liberian': 0.007407407407407408,
  'ec': 0.003703703703703704,
  'epp': 0.003703703703703704,
  'wef': 0.003703703703703704,
  '£400m': 0.003703703703703704,
  '£173': 0.003703703703703704,
  'elaa': 0.003703703703703704,
  'iata': 0.003703703703703704,
  'eraa': 0.003703703703703704,
  'cips': 0.003703703703703704,
  'pmi': 0.003703703703703704,
  'isp': 0.003703703703703704,
  'saic': 0.003703703703703704,
  '£691m': 0.003703703703703704,
  '£8.82bn': 0.003703703703703704,
  'osi': 0.003703703703703704,
  '£1.87bn': 0.003703703703703704,
  '£277m': 0.003703703703703704,
  'cam': 0.003703703703703704,
  'cfd': 0.003703703703703704,
  '£3.2bn': 0.003703703703703704,
  'kse': 0.003703703703703704,
  'ifs': 0.003703703703703704,
  '£134m': 0.003703703703703704,
  '£3.4bn': 0.003703703703703704,
  '£117m': 0.003703703703703704,
  'cao': 0.003703703703703704,
  '£29bn': 0.003703703703703704,
  '£264': 0.003703703703703704,
  '£4.4bn': 0.003703703703703704,
  '£530m': 0.003703703703703704,
  'ni': 0.003703703703703704,
  '£182.5m': 0.003703703703703704,
  'insee': 0.003703703703703704,
  '£290m': 0.003703703703703704,
  '£931m': 0.003703703703703704,
  'pfi': 0.003703703703703704,
  'afp': 0.003703703703703704,
  '£28.85m': 0.003703703703703704,
  'wsj': 0.003703703703703704,
  'ups': 0.003703703703703704,
  '£479m': 0.003703703703703704,
  'compliance': 0.003703703703703704},
 ('£5.8bn', 'fraud'): {')': 1.0},
 (')', 'never'): {'fraud': 1.0},
 ('fraud', 'made'): {'never': 1.0},
 ('never', 'accounting'): {'made': 1.0},
 ('made', 'decisions'): {'accounting': 1.0},
 ('accounting', 'a'): {'decisions': 0.5, 'during': 0.5},
 ('decisions', 'witness'): {'a': 1.0},
 ('a', 'has'): {'witness': 0.125,
  'study': 0.125,
  'court': 0.125,
  'strategy': 0.125,
  'judge': 0.125,
  'person': 0.125,
  'survey': 0.125,
  'charity': 0.125},
 ('witness', 'told'): {'has': 1.0},
 ('has', 'jurors'): {'told': 1.0},
 ('told', '.'): {'jurors': 0.05555555555555555,
  'reuters': 0.8333333333333334,
  'bloomberg': 0.05555555555555555,
  'ap': 0.05555555555555555},
 ('jurors', 'david'): {'.': 1.0},
 ('.', 'myers'): {'david': 0.3333333333333333, 'mr': 0.6666666666666666},
 ('david', 'made'): {'myers': 1.0},
 ('myers', 'the'): {'made': 1.0},
 ('made', 'comments'): {'the': 1.0},
 ('the', 'under'): {'comments': 0.2, 'firms': 0.4, 'link': 0.2, 'case': 0.2},
 ('comments', 'questioning'): {'under': 1.0},
 ('under', 'by'): {'questioning': 1.0},
 ('questioning', 'defence'): {'by': 1.0},
 ('by', 'lawyers'): {'defence': 1.0},
 ('defence', 'who'): {'lawyers': 1.0},
 ('lawyers', 'have'): {'who': 1.0},
 ('who', 'been'): {'have': 0.25, 'had': 0.125, 'has': 0.625},
 ('have', 'arguing'): {'been': 1.0},
 ('been', 'that'): {'arguing': 0.125,
  'speculation': 0.125,
  'hoping': 0.125,
  'rumours': 0.125,
  'preferable': 0.125,
  'advised': 0.25,
  'reported': 0.125},
 ('arguing', 'mr'): {'that': 1.0},
 ('that', 'ebbers'): {'mr': 1.0},
 ('mr', 'was'): {'ebbers': 0.11764705882352941,
  'bewlay': 0.058823529411764705,
  'yushchenko': 0.11764705882352941,
  'kerekou': 0.058823529411764705,
  'kok': 0.11764705882352941,
  'bell': 0.11764705882352941,
  'royer': 0.058823529411764705,
  'elgindy': 0.058823529411764705,
  'seifert': 0.058823529411764705,
  'mcmanus': 0.058823529411764705,
  'khodorkovsky': 0.058823529411764705,
  'shevardnadze': 0.058823529411764705,
  'brown': 0.058823529411764705},
 ('ebbers', 'not'): {'was': 1.0},
 ('was', 'responsible'): {'not': 0.3333333333333333,
  'still': 0.3333333333333333,
  'primarily': 0.3333333333333333},
 ('not', 'for'): {'responsible': 0.1111111111111111,
  'ready': 0.2222222222222222,
  'work': 0.1111111111111111,
  'enough': 0.1111111111111111,
  'rebidding': 0.1111111111111111,
  'available': 0.1111111111111111,
  'necessarily': 0.1111111111111111,
  'good': 0.1111111111111111},
 ('responsible', 'worldcom'): {'for': 1.0},
 ('for', 's'): {'worldcom': 0.06666666666666667,
  'carnival': 0.06666666666666667,
  'japan': 0.06666666666666667,
  'australia': 0.06666666666666667,
  'rover': 0.06666666666666667,
  'cairn': 0.06666666666666667,
  'kraft': 0.06666666666666667,
  'inbev': 0.06666666666666667,
  'china': 0.06666666666666667,
  'cuba': 0.06666666666666667,
  'marianne': 0.06666666666666667,
  'merrill': 0.06666666666666667,
  'europe': 0.06666666666666667,
  'xstrata': 0.06666666666666667,
  'egypt': 0.06666666666666667},
 ('worldcom', 'problems'): {'s': 1.0},
 ('s', '.'): {'problems': 0.009615384615384616,
  'shares': 0.038461538461538464,
  'economy': 0.04807692307692308,
  'decline': 0.009615384615384616,
  'founder': 0.009615384615384616,
  'engines': 0.009615384615384616,
  'announcement': 0.019230769230769232,
  'profits': 0.019230769230769232,
  'appointment': 0.009615384615384616,
  'actions': 0.009615384615384616,
  'shareholders': 0.019230769230769232,
  'deputy': 0.009615384615384616,
  'growth': 0.019230769230769232,
  'ryanair': 0.019230769230769232,
  'elections': 0.019230769230769232,
  'favour': 0.009615384615384616,
  'sales': 0.009615384615384616,
  'enarsa': 0.009615384615384616,
  'move': 0.009615384615384616,
  'website': 0.009615384615384616,
  'troubles': 0.009615384615384616,
  'future': 0.019230769230769232,
  'chief': 0.009615384615384616,
  'different': 0.019230769230769232,
  'auction': 0.009615384615384616,
  'poorest': 0.009615384615384616,
  'offer': 0.019230769230769232,
  'policyholders': 0.009615384615384616,
  'activities': 0.009615384615384616,
  'assets': 0.009615384615384616,
  'closure': 0.009615384615384616,
  'cuts': 0.009615384615384616,
  'interest': 0.009615384615384616,
  'administration': 0.009615384615384616,
  'debts': 0.009615384615384616,
  'spokesman': 0.009615384615384616,
  'population': 0.009615384615384616,
  'currency': 0.009615384615384616,
  'enron': 0.009615384615384616,
  'bid': 0.009615384615384616,
  'call': 0.009615384615384616,
  'decisions': 0.009615384615384616,
  'requirement': 0.009615384615384616,
  'chairman': 0.009615384615384616,
  'history': 0.009615384615384616,
  'misdeeds': 0.019230769230769232,
  'collapse': 0.038461538461538464,
  'proposal': 0.009615384615384616,
  'group': 0.009615384615384616,
  'barn': 0.009615384615384616,
  'rules': 0.019230769230769232,
  'hopes': 0.009615384615384616,
  'child': 0.009615384615384616,
  'events': 0.009615384615384616,
  'lawsuit': 0.009615384615384616,
  'finances': 0.028846153846153848,
  'board': 0.019230769230769232,
  'figures': 0.019230769230769232,
  'origin': 0.009615384615384616,
  'ongc': 0.009615384615384616,
  'airport': 0.009615384615384616,
  'strength': 0.009615384615384616,
  'guardian': 0.009615384615384616,
  'disaster': 0.009615384615384616,
  'election': 0.009615384615384616,
  'sap': 0.009615384615384616,
  'lawyers': 0.009615384615384616,
  'cnpc': 0.009615384615384616,
  'accountants': 0.009615384615384616,
  'performance': 0.009615384615384616,
  'advantage': 0.009615384615384616,
  'party': 0.009615384615384616,
  'coffers': 0.009615384615384616,
  'budget': 0.009615384615384616,
  'contract': 0.009615384615384616,
  'behaviour': 0.009615384615384616,
  'credit': 0.009615384615384616,
  'identity': 0.009615384615384616,
  'management': 0.009615384615384616},
 ('problems', 'the'): {'.': 0.8333333333333334, 'with': 0.16666666666666666},
 ('.', 'phone'): {'the': 1.0},
 ('the', 'company'): {'phone': 0.058823529411764705,
  'parent': 0.058823529411764705,
  'us': 0.058823529411764705,
  'seattle-based': 0.058823529411764705,
  'florida': 0.058823529411764705,
  'shell': 0.058823529411764705,
  'media': 0.11764705882352941,
  'ailing': 0.058823529411764705,
  'netherlands-based': 0.058823529411764705,
  'combined': 0.058823529411764705,
  'bankrupt': 0.058823529411764705,
  'bigger': 0.058823529411764705,
  'german': 0.058823529411764705,
  'new': 0.058823529411764705,
  'holding': 0.058823529411764705,
  'us-based': 0.058823529411764705},
 ('phone', 'collapsed'): {'company': 1.0},
 ('company', 'in'): {'collapsed': 0.1111111111111111,
  'which': 0.4444444444444444,
  '-': 0.1111111111111111,
  'was': 0.2222222222222222,
  'jagran': 0.1111111111111111},
 ('collapsed', '2002'): {'in': 1.0},
 ('in', 'and'): {'2002': 0.006896551724137931,
  '2006': 0.006896551724137931,
  'india': 0.013793103448275862,
  'grants': 0.006896551724137931,
  'iraq': 0.027586206896551724,
  '2003': 0.034482758620689655,
  'europe': 0.034482758620689655,
  'education': 0.006896551724137931,
  'china': 0.013793103448275862,
  'engines': 0.006896551724137931,
  'aggressive': 0.006896551724137931,
  'russia': 0.013793103448275862,
  '2004': 0.04827586206896552,
  'december': 0.04827586206896552,
  'turkmenistan': 0.006896551724137931,
  'egypt': 0.006896551724137931,
  'germany': 0.020689655172413793,
  '2001': 0.027586206896551724,
  'asia': 0.006896551724137931,
  'london': 0.041379310344827586,
  '2005': 0.034482758620689655,
  '2003.': 0.006896551724137931,
  'australia': 0.006896551724137931,
  'investment': 0.006896551724137931,
  'africa': 0.013793103448275862,
  'it': 0.006896551724137931,
  'buildings': 0.006896551724137931,
  'order': 0.020689655172413793,
  'indonesia': 0.013793103448275862,
  'nepal': 0.006896551724137931,
  'manufacturing': 0.013793103448275862,
  'october': 0.020689655172413793,
  'political': 0.006896551724137931,
  '1973': 0.006896551724137931,
  'phuket': 0.006896551724137931,
  'profits': 0.006896551724137931,
  'january': 0.027586206896551724,
  'us': 0.006896551724137931,
  'february': 0.006896551724137931,
  'telecommunication': 0.006896551724137931,
  'italy': 0.013793103448275862,
  '1998': 0.006896551724137931,
  'november': 0.020689655172413793,
  'row': 0.006896551724137931,
  'mining': 0.006896551724137931,
  'premium': 0.006896551724137931,
  'coverage': 0.006896551724137931,
  'france': 0.006896551724137931,
  'jail': 0.006896551724137931,
  'banking': 0.006896551724137931,
  'eastern': 0.006896551724137931,
  'elan': 0.006896551724137931,
  'rotterdam': 0.006896551724137931,
  'natural': 0.006896551724137931,
  'value': 0.006896551724137931,
  '1984': 0.006896551724137931,
  'fines': 0.006896551724137931,
  'rebuilding': 0.006896551724137931,
  'florida': 0.006896551724137931,
  'august': 0.006896551724137931,
  'venezuela': 0.006896551724137931,
  'taxes': 0.013793103448275862,
  'scotland': 0.006896551724137931,
  '1997': 0.006896551724137931,
  'ireland': 0.006896551724137931,
  '2000': 0.013793103448275862,
  'fits': 0.006896551724137931,
  'oil': 0.006896551724137931,
  'gas': 0.006896551724137931,
  'japan': 0.006896551724137931,
  'exports': 0.006896551724137931,
  'regulations': 0.006896551724137931,
  'abeyance': 0.006896551724137931,
  'airports': 0.006896551724137931,
  'bonus': 0.006896551724137931,
  'telecoms': 0.006896551724137931,
  'kazakhstan': 0.006896551724137931,
  'defence': 0.006896551724137931,
  'spain': 0.006896551724137931,

In [37]:
texts.iloc[0].split("\n")

['worldcom boss  left books alone  former worldcom boss bernie ebbers  who is accused of overseeing an $11bn (£5.8bn) fraud  never made accounting decisions  a witness has told jurors.  david myers made the comments under questioning by defence lawyers who have been arguing that mr ebbers was not responsible for worldcom s problems. the phone company collapsed in 2002 and prosecutors claim that losses were hidden to protect the firm s shares. mr myers has already pleaded guilty to fraud and is assisting prosecutors.  on monday  defence lawyer reid weingarten tried to distance his client from the allegations. during cross examination  he asked mr myers if he ever knew mr ebbers  make an accounting decision  .  not that i am aware of   mr myers replied.  did you ever know mr ebbers to make an accounting entry into worldcom books   mr weingarten pressed.  no   replied the witness. mr myers has admitted that he ordered false accounting entries at the request of former worldcom chief financial officer scott sullivan. defence lawyers have been trying to paint mr sullivan  who has admitted fraud and will testify later in the trial  as the mastermind behind worldcom s accounting house of cards.  mr ebbers  team  meanwhile  are looking to portray him as an affable boss  who by his own admission is more pe graduate than economist. whatever his abilities  mr ebbers transformed worldcom from a relative unknown into a $160bn telecoms giant and investor darling of the late 1990s. worldcom s problems mounted  however  as competition increased and the telecoms boom petered out. when the firm finally collapsed  shareholders lost about $180bn and 20 000 workers lost their jobs. mr ebbers  trial is expected to last two months and if found guilty the former ceo faces a substantial jail sentence. he has firmly declared his innocence.']

output[] empty list to store each spunned paragraph

In [38]:
def spin_document(doc):
  # split the document into lines (paragraphs)
  lines = doc.split("\n")
  output = []
  for line in lines:
    if line:
      new_line = spin_line(line)
    else:
      new_line = line
    output.append(new_line)
  return "\n".join(output)

In [39]:
detokenizer = TreebankWordDetokenizer()

In [40]:
texts.iloc[0].split("\n")[0]

'worldcom boss  left books alone  former worldcom boss bernie ebbers  who is accused of overseeing an $11bn (£5.8bn) fraud  never made accounting decisions  a witness has told jurors.  david myers made the comments under questioning by defence lawyers who have been arguing that mr ebbers was not responsible for worldcom s problems. the phone company collapsed in 2002 and prosecutors claim that losses were hidden to protect the firm s shares. mr myers has already pleaded guilty to fraud and is assisting prosecutors.  on monday  defence lawyer reid weingarten tried to distance his client from the allegations. during cross examination  he asked mr myers if he ever knew mr ebbers  make an accounting decision  .  not that i am aware of   mr myers replied.  did you ever know mr ebbers to make an accounting entry into worldcom books   mr weingarten pressed.  no   replied the witness. mr myers has admitted that he ordered false accounting entries at the request of former worldcom chief financial officer scott sullivan. defence lawyers have been trying to paint mr sullivan  who has admitted fraud and will testify later in the trial  as the mastermind behind worldcom s accounting house of cards.  mr ebbers  team  meanwhile  are looking to portray him as an affable boss  who by his own admission is more pe graduate than economist. whatever his abilities  mr ebbers transformed worldcom from a relative unknown into a $160bn telecoms giant and investor darling of the late 1990s. worldcom s problems mounted  however  as competition increased and the telecoms boom petered out. when the firm finally collapsed  shareholders lost about $180bn and 20 000 workers lost their jobs. mr ebbers  trial is expected to last two months and if found guilty the former ceo faces a substantial jail sentence. he has firmly declared his innocence.'

In [41]:
detokenizer.detokenize(word_tokenize(texts.iloc[0].split("\n")[0]))

'worldcom boss left books alone former worldcom boss bernie ebbers who is accused of overseeing an $11bn (£5.8bn) fraud never made accounting decisions a witness has told jurors . david myers made the comments under questioning by defence lawyers who have been arguing that mr ebbers was not responsible for worldcom s problems . the phone company collapsed in 2002 and prosecutors claim that losses were hidden to protect the firm s shares . mr myers has already pleaded guilty to fraud and is assisting prosecutors . on monday defence lawyer reid weingarten tried to distance his client from the allegations . during cross examination he asked mr myers if he ever knew mr ebbers make an accounting decision . not that i am aware of mr myers replied . did you ever know mr ebbers to make an accounting entry into worldcom books mr weingarten pressed . no replied the witness . mr myers has admitted that he ordered false accounting entries at the request of former worldcom chief financial officer scott sullivan . defence lawyers have been trying to paint mr sullivan who has admitted fraud and will testify later in the trial as the mastermind behind worldcom s accounting house of cards . mr ebbers team meanwhile are looking to portray him as an affable boss who by his own admission is more pe graduate than economist . whatever his abilities mr ebbers transformed worldcom from a relative unknown into a $160bn telecoms giant and investor darling of the late 1990s . worldcom s problems mounted however as competition increased and the telecoms boom petered out . when the firm finally collapsed shareholders lost about $180bn and 20 000 workers lost their jobs . mr ebbers trial is expected to last two months and if found guilty the former ceo faces a substantial jail sentence . he has firmly declared his innocence.'

In [42]:
def sample_word(d):
  p0 = np.random.random()
  cumulative = 0
  for t, p in d.items():
    cumulative += p
    if p0 < cumulative:
      return t
  assert(False) # should never get here

In [43]:
def spin_line(line):
  tokens = word_tokenize(line)
  i = 0
  output = [tokens[0]]
  while i < (len(tokens) - 2):
    t_0 = tokens[i]
    t_1 = tokens[i + 1]
    t_2 = tokens[i + 2]
    key = (t_0, t_2)
    p_dist = probs[key]
    if len(p_dist) > 1 and np.random.random() < 0.3:
      # let's replace the middle word
      middle = sample_word(p_dist)
      output.append(t_1)
      output.append("<" + middle + ">")
      output.append(t_2)

      # we won't replace the 3rd token since the middle
      # token was dependent on it
      # instead, skip ahead 2 steps
      i += 2
    else:
      # we won't replace this middle word
      output.append(t_1)
      i += 1
  # append the final token - only if there was no replacement
  if i == len(tokens) - 2:
    output.append(tokens[-1])
  return detokenizer.detokenize(output)

In [44]:
np.random.seed(1234)

In [45]:
i = np.random.choice(texts.shape[0])
doc = texts.iloc[i]
new_doc = spin_document(doc)

In [46]:
print(textwrap.fill(
    new_doc, replace_whitespace=False, fix_sentence_endings=True))

honda wins china copyright ruling japan s honda has won a copyright
case in beijing further evidence that china is taking <eyeing> a
tougher line on protecting intellectual property rights <market>. a
<the> court ruled that chongqing lifan industry group must stop
selling honda brand motorbikes and said it must <to> pay 1.47m yuan
($177 600) in compensation <november>. internationally recognized
regulation is now <primarily> a key part of china <china> s plans for
developing its economy analysts said . beijing also has been
threatened <engaged> with sanctions if it fails to clamp down .
chinese firms copy products ranging from computer software and spark
plugs to baby milk and compact discs . despite the fact <moment> that
product piracy is a major problem foreign companies have only
occasionally won cases and the compensation awarded has usually <not>
been small . still recent rulings <rulings> and announcements <ntpc>
will have boosted optimism that attitudes are changing . earlier
<earlier> this week china said that <profit> in future it will punish
violators of intellectual <their> property rights with up to seven
years in jail <november>. and on tuesday paws incorporated - the owner
of the rights to garfield <prefer> the cat <1990s> - won a court
battle against a publishing house that violated its copyright . other
firms that have taken legal action in china <line> with varying
degrees of success include yamaha general motors and toyota . the
problem of piracy is not limited to <.> china however and <urged> the
potential for profit <warning> is huge <accelerating>. the european
<soviet> union estimates that <by> the global trade <economy> in
pirated wares is worth more than 200bn <200bn> euros a year (£140bn;
$258bn) or about 5% of total <the> world trade . and <however> it is
growing . between 1998 and 2002 <restructuring> the number of
counterfeit or pirated goods intercepted at the eu s external borders
increased by more <more> than 800% it said . last month <month> the eu
<industry> said it will start monitoring china ukraine and russia to
ensure they are going after pirated goods . other countries
<countries> on the eu s hit list include thailand brazil south korea
and indonesia . any <other> countries that <which> are not making
<strong> enough of an effort could be dragged to the world trade
organisation (wto) a step <consortium> that could trigger economic
sanctions the eu <company> warned.